#!/usr/bin/env python3
"""Presentation project checker.

Three modes, selected by what the project contains (Phase T2):

1. handoff-first project (presentation-manifest.json present):
   delegates coverage checking to validate_manifest.py (story coverage,
   must-have visual coverage, evidence traceability, asset existence) and
   keeps the structural checks below. A `--handoff <path>` argument is
   forwarded for hash/evidence cross-checks.

2. raw-input project with required_sections.txt:
   checks that every non-empty line of that file appears in slides.qmd
   (the project's own narrative contract).

3. raw-input project without a narrative contract:
   structural checks only, plus a WARNING that no narrative contract exists —
   the checker never decides whether a slide is good or a mental model is deep
   (that stays a semantic/visual review).

Structural checks in every mode: core files exist, no visible generator text,
referenced images exist.
"""
from pathlib import Path
import re
import subprocess
import sys

root = Path(__file__).resolve().parents[1]
errors = []
warnings = []

for name in ["slides.qmd", "_quarto.yml", "styles.scss", "Makefile"]:
    if not (root / name).is_file():
        errors.append(f"missing {name}")

qmd = (root / "slides.qmd").read_text(encoding="utf-8") if (root / "slides.qmd").is_file() else ""

for bad in ["generated by", "created with", "AI generated", "Presentation Skill"]:
    if bad.lower() in qmd.lower():
        errors.append(f"visible generator text: {bad}")

for img in re.findall(r"!\[[^\]]*\]\(([^)]+)\)", qmd):
    p = root / img.split("{", 1)[0].strip()
    if not p.exists():
        errors.append(f"missing referenced image: {img}")

manifest = root / "presentation-manifest.json"
sections = root / "required_sections.txt"

if manifest.is_file():
    # Mode 1: handoff-first project — coverage checks own the narrative side.
    cmd = [sys.executable, str(root / "scripts" / "validate_manifest.py"),
           "--manifest", str(manifest)]
    if "--handoff" in sys.argv:
        i = sys.argv.index("--handoff")
        cmd += ["--handoff", sys.argv[i + 1]]
    result = subprocess.run(cmd, capture_output=True, text=True)
    if result.returncode != 0:
        errors.extend(line for line in result.stderr.splitlines() if line.startswith("ERROR:"))
    if result.stdout:
        print(result.stdout.strip())
elif sections.is_file():
    # Mode 2: raw-input project with an explicit narrative contract.
    for line in sections.read_text(encoding="utf-8").splitlines():
        token = line.strip()
        if token and token not in qmd:
            errors.append(f"missing narrative keyword: {token}")
else:
    warnings.append(
        "no presentation-manifest.json and no required_sections.txt — "
        "raw-input mode without a narrative contract; story authority is manual")

if warnings:
    for w in warnings:
        print("WARNING:", w, file=sys.stderr)

if errors:
    for e in errors:
        print("ERROR:", e, file=sys.stderr)
    raise SystemExit(1)

print("OK: project structure checks passed")
