project:
  type: default
  output-dir: _site

format:
  revealjs:
    theme: [default, styles.scss]
    width: 1600
    height: 900
    margin: 0.065
    center: false
    slide-number: true
    controls: true
    controls-tutorial: false
    progress: true
    transition: none
    background-transition: none
    navigation-mode: linear
    hash: true
    history: true
    embed-resources: true
    self-contained-math: true
    incremental: false
    code-overflow: wrap

execute:
  echo: false
  warning: false
