#!/usr/bin/env python3
from pathlib import Path
import re, sys
root=Path(__file__).resolve().parents[1]
errors=[]
for name in ["slides.qmd","_quarto.yml","styles.scss","Makefile"]:
    if not (root/name).is_file(): errors.append(f"missing {name}")
qmd=(root/"slides.qmd").read_text(encoding="utf-8") if (root/"slides.qmd").is_file() else ""
required=["Pass", "合并", "核心流程", "依赖模型", "主要缺陷", "改进建议", "总结"]
for x in required:
    if x not in qmd: errors.append(f"missing narrative keyword: {x}")
for bad in ["generated by","created with","AI generated","Presentation Skill"]:
    if bad.lower() in qmd.lower(): errors.append(f"visible generator text: {bad}")
for img in re.findall(r'!\[[^\]]*\]\(([^)]+)\)', qmd):
    p=(root/img.split('{',1)[0].strip())
    if not p.exists(): errors.append(f"missing referenced image: {img}")
if errors:
    for e in errors: print("ERROR:",e,file=sys.stderr)
    raise SystemExit(1)
print("OK: Quarto project structure and required sections present")
